title: Taverns & Tales
description: Dungeons and Dragons hosted at Austin Beerwork's Sprinkle Valley location.
domain: taverntales.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://taverntales.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "tavernsandtales"      # place folder name if the site is served in a subfolder

